
name: spicy_tulip_pos
description: Fixed version with WooCommerce integration and price formatting
version: 1.0.1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.18.1
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
